name: Run ElEconomista Scraper hourly

on:
  schedule:
    - cron: "0 * * * *"   # cada hora (UTC)
  workflow_dispatch: {}    # permite lanzarlo a mano

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # necesario para poder hacer commit desde el workflow

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run scraper
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          DB_PATH: data/seen.db
        run: |
          python scraper.py

      - name: Commit & push updated seen.db
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/seen.db
          git diff --cached --quiet && echo "No DB changes" || (git commit -m "chore: update seen.db [skip ci]" && git push)
